@extends('layouts.app')

@section('title', 'Pascal Legacy Telemetry')

@section('content')
<div class="container-fluid mt-4">
    <div class="row mb-4 fade-in-up">
        <div class="col-12">
            <div class="glass-card p-4">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h2 class="text-gradient mb-0">
                        <i class="bi bi-cpu"></i> Pascal Legacy CSV Telemetry
                    </h2>
                    <div>
                        <a href="{{ route('legacy.export') }}" class="btn btn-success me-2">
                            <i class="bi bi-file-earmark-excel"></i> Export XLSX
                        </a>
                        <a href="{{ url('/legacy/stats') }}" class="btn btn-cosmic">
                            <i class="bi bi-graph-up"></i> Statistics
                        </a>
                    </div>
                </div>
                <p class="text-light-muted">
                    Telemetry data generated by Free Pascal CSV generator with proper data types: 
                    ISO timestamps, TRUE/FALSE booleans, floating point numbers, and CSV-escaped strings
                </p>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-12">
            <div class="glass-card p-4 fade-in">
                <h5 class="text-gradient mb-3">
                    <i class="bi bi-funnel"></i> Telemetry Data
                    <span class="badge bg-cosmic ms-2">{{ count($telemetry) }} records</span>
                </h5>

                <div id="tableControls" class="mb-3"></div>

                <div class="table-responsive">
                    <table id="telemetryTable" class="table table-dark table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Timestamp</th>
                                <th>Sensor Name</th>
                                <th>Voltage (V)</th>
                                <th>Temperature (°C)</th>
                                <th>Pressure (hPa)</th>
                                <th>Online</th>
                                <th>Calibrated</th>
                                <th>Status</th>
                                <th>Source File</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($telemetry as $record)
                            <tr class="hover-lift">
                                <td>{{ $record->id }}</td>
                                <td>
                                    <span class="badge bg-info">
                                        {{ \Carbon\Carbon::parse($record->timestamp)->format('Y-m-d H:i:s') }}
                                    </span>
                                </td>
                                <td>
                                    <span class="badge bg-secondary">
                                        {{ $record->sensor_name }}
                                    </span>
                                </td>
                                <td class="text-warning">{{ number_format($record->voltage, 2) }}</td>
                                <td class="text-{{ $record->temperature > 50 ? 'danger' : ($record->temperature < 0 ? 'info' : 'success') }}">
                                    {{ number_format($record->temperature, 2) }}
                                </td>
                                <td class="text-primary">{{ number_format($record->pressure, 2) }}</td>
                                <td>
                                    @if($record->is_online)
                                        <span class="badge bg-success">
                                            <i class="bi bi-check-circle"></i> TRUE
                                        </span>
                                    @else
                                        <span class="badge bg-secondary">
                                            <i class="bi bi-x-circle"></i> FALSE
                                        </span>
                                    @endif
                                </td>
                                <td>
                                    @if($record->is_calibrated)
                                        <span class="badge bg-success">
                                            <i class="bi bi-check-circle"></i> TRUE
                                        </span>
                                    @else
                                        <span class="badge bg-warning">
                                            <i class="bi bi-exclamation-triangle"></i> FALSE
                                        </span>
                                    @endif
                                </td>
                                <td>
                                    <span class="badge bg-{{ 
                                        str_contains($record->status, 'Operational') ? 'success' : 
                                        (str_contains($record->status, 'Calibration') ? 'warning' : 'secondary') 
                                    }}">
                                        {{ $record->status }}
                                    </span>
                                </td>
                                <td class="text-muted small">{{ $record->source_file }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    // Инициализируем DataTableManager
    const table = new DataTableManager('telemetryTable', {
        searchable: true,
        exportable: true,
        exportFilename: 'pascal_legacy_telemetry'
    });
    
    // Создаём UI контролы
    table.createTableControls('tableControls');
    
    // Добавляем фильтры по типам сенсоров
    const sensors = [...new Set(Array.from(document.querySelectorAll('#telemetryTable tbody tr')).map(row => 
        row.cells[2].textContent.trim()
    ))];
    
    table.addFilter('Sensor Type', 'Sensor Name', sensors.map(s => ({value: s, label: s})));
    
    // Фильтр по статусу online
    table.addFilter('Online Status', 'Online', [
        {value: 'TRUE', label: 'Online'},
        {value: 'FALSE', label: 'Offline'}
    ]);
    
    // Фильтр по калибровке
    table.addFilter('Calibration', 'Calibrated', [
        {value: 'TRUE', label: 'Calibrated'},
        {value: 'FALSE', label: 'Not Calibrated'}
    ]);
});
</script>
@endsection
